spring.application.name=alumni-portal

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://sivakumar:siva@cluster0.ufpyq.mongodb.net/alumni_db

# Prevent Spring Security from locking down all endpoints by default
# We will define custom security configuration to permit all for now, 
# and just use BCryptPasswordEncoder.
spring.main.allow-bean-definition-overriding=true
